import TrustBadge from './TrustBadge.jsx'

const ITEMS = [
  {
    variant: 'verified',
    text: 'Official information from GOV.UK, the UK Home Office, or VFS Global.',
  },
  {
    variant: 'community',
    text: 'Reported by real applicants on Reddit, Quora, forums and blogs — not official policy.',
  },
  {
    variant: 'ai',
    text: 'Generated by the AI Copilot, personalised to your question.',
  },
]

// Explains the three-layer trust model wherever badges appear.
export default function TrustLegend() {
  return (
    <div className="trust-legend" aria-label="What the trust badges mean">
      <span className="trust-legend__title">How to read this information</span>
      {ITEMS.map(({ variant, text }) => (
        <div key={variant} className="trust-legend__item">
          <TrustBadge variant={variant} />
          <span className="trust-legend__text">{text}</span>
        </div>
      ))}
    </div>
  )
}
